### ISSUE TITLE
Check on issues with `max(x, 0)` from #124

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-sandbox#126]
From #124:
> There are some weirdness when I tried to tight the relu to just `max(x, 0)` probably related to the tests I use. I think are addressed in: https://github.com/plaidml/tpp-sandbox/pull/115/commits but more investigation is needed.

@chelini can you expand on what do you mean by weirdness and how do we know it's "fixed".

**Comment by chelini** [comment]
We enter an infinite loop when converting linalg to tpp. Partially this has been addressed in https://github.com/plaidml/tpp-sandbox/pull/115/commits/fd69e96e5fe70441ab269219f5f7ca723b4da1d0 but I need to look more deeply tomorrow.

**Comment by chelini** [comment]
I think you hit the same bug a bit of time ago

**Comment by chelini** [comment]
This was my misunderstanding. We still need to fix the issue of restricting relu to `maxf(x, 0)` but the infinite loop in reshape2D is not fixed in #87
