### ISSUE TITLE
Fix match `maxf(x, N)` to relu

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-sandbox#130]
As exposed in #128, a `linalg.generic` with `arith.maxf(x, N)` (with N any non-zero number) will map to ReLU, which is wrong.

To map to ReLU, N must be `0.0`.

**Comment by chelini** [comment]
One problem here is that linalg.generic is not isolated from above so you can have multiple choices. Two of them that come to my mind are:
```
cts = arith.constant 0.0 : f32
linalg.generic ins(%arg0: tensor<3x3xf32>) {
^bb(%arg1: f32)
   %0 = arith.maxf(%arg1, %cst)
   linalg.yield %0
}
```
or

```
linalg.generic ins(%arg0: tensor<3x3xf32>) out(%arg1: tensor<3x3xf32>) {
^bb(%arg2 : f32, %arg3 : f32)
  %0 = arith.maxf(%arg2, %arg3)
  linalg.yield %0
}
```
Assuming %arg1 to be tensor filled with zeros.

**Comment by rengolin** [comment]
This doesn't need to be isolated from above, we just need to follow both operands and make sure one of them is the induction value and the other is a constant with value `0.0`.

The first case seems good to me for converting other representations into `maxf`, but we also need to be aware of how front-ends represent that, if they use `maxf` too (we can worry about this later).
