### ISSUE TITLE
Build the tpp compiler with sanitizers on CI

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-sandbox#136]
As exposed on [here](https://github.com/plaidml/tpp-sandbox/commit/4e37af6c087205021ac6e16db04f2503a4a6db30#commitcomment-89099234), we have memory leaks in the code.

We need to either always build the compiler with sanitizers or create a separate build for sanitizers. Since the compiler is small and we don't use it for other things, we might just do the former.

@chelini @hfp

**Comment by chelini** [comment]
There is already an option to build it with the sanitizer `USE_SANITIZER=Address;Undefined` so a simple build should do the trick.

**Comment by rengolin** [comment]
Ok, got a local build and managed to reproduce your error:

Adding `-DUSE_SANITIZER="Address;Memory;Leak;Undefined"` makes test `Integration/tpp-identity.mlir` fail with

```
: 'RUN: at line 1';   /home/rengolin/devel/intel/tpp-sandbox/build/main/bin/tpp-opt /home/rengolin/devel/intel/tpp-sandbox/test/Integration/tpp-identity.mlir -canonicalize -empty-tensor-to-alloc-tensor -one-shot-bufferize="bufferize-function-boundaries allow-return-allocs function-boundary-type-conversion=identity-layout-map" -canonicalize -drop-equivalent-buffer-results -finalizing-bufferize -convert-check-to-func  -convert-linalg-to-tpp -convert-tpp-to-xsmm -convert-xsmm-to-func -convert-vector-to-scf -convert-scf-to-cf | /home/rengolin/devel/intel/tpp-sandbox/build/main/bin/tpp-run   -e entry -entry-point-result=void   -shared-libs=/home/rengolin/devel/llvm-project/build/sandbox/./lib/libmlir_c_runner_utils.so,/home/rengolin/devel/intel/tpp-sandbox/build/main/lib//libtpp_c_runner_utils.so
--
Exit Code: 1

Command Output (stderr):
--

=================================================================
==12742==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 384 byte(s) in 1 object(s) allocated from:
    #0 0x7f7060abfa89 in __interceptor_malloc /usr/src/debug/gcc/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f7060637014  (<unknown module>)
    #2 0x7f706063754c  (<unknown module>)
    #3 0x534aa8aec4fc4eff  (<unknown module>)

SUMMARY: AddressSanitizer: 384 byte(s) leaked in 1 allocation(s).
```

Does not help much but once we fix this, we need to enable that option to all CI builds (in BuildKite at least) to make sure we don't regress.

Perhaps Valgrid may be more helpful in zeroing on the actual problem?

**Comment by rengolin** [comment]
This is after #137 was merged, so there's something else out there.

**Comment by rengolin** [comment]
Ha! #138, ignore me.

**Comment by rengolin** [comment]
Sanitizer build green: https://buildkite.com/intel/tpp-compiler/builds/578
