### ISSUE TITLE
`mlp_kernel.mlir` in benchmarks doesn't work without `-pre-bufferize`

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-sandbox#142]
We're removing `-pre-bufferize` from tests, but the benchmark `mlp_kernel.mlir`, which is now moving to the test infra, is badly transformed (and produces wrong results) without it.

When initializing the source tensors with all 1s, expecting the results as all 9s, I still get all 1s (as if the tensor hasn't changed).

I haven't looked at the problem yet, but my guess is some alloc / copy that isn't being transformed correctly to memrefs.

Once #140 is merged, the reproduction is just to remove the `-pre-bufferize` option from the test in `test/Benchmarks` and run `check-tpp-opt`.

Alternatively, remove the option from `benchmarks/mlp/run-mlp.sh` and run that benchmark.

**Comment by chelini** [comment]
Fixed in ed9a4623d2bc0af0e4b3abcc4b09312f56da58dd
