### ISSUE TITLE
Crash when building vector print in `tpp-run`

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-sandbox#158]
As reported in #45:
```
********************
Testing:  0.. 10.. 20.. 30.. 40.. 50.. 60..
FAIL: TPP_OPT :: Benchmarks/simple-gemm.mlir (69 of 71)
******************** TEST 'TPP_OPT :: Benchmarks/simple-gemm.mlir' FAILED ********************
Script:
--
: 'RUN: at line 1';   /home/asiemien/tpp-sandbox/build/bin/tpp-opt /home/asiemien/tpp-sandbox/test/Benchmarks/simple-gemm.mlir -map-linalg-to-tpp  -one-shot-bufferize="bufferize-function-boundaries allow-return-allocs function-boundary-type-conversion=identity-layout-map"  -drop-equivalent-buffer-results -finalizing-bufferize -canonicalize  -convert-linalg-to-tpp -convert-tpp-to-xsmm  -convert-xsmm-to-func |  /home/asiemien/tpp-sandbox/build/bin/tpp-run   -e entry -entry-point-result=void   -shared-libs=/home/asiemien/llvm-project/build/./lib/libmlir_c_runner_utils.so,/home/asiemien/tpp-sandbox/build/lib//libtpp_c_runner_utils.so |  /home/asiemien/llvm-project/build/bin/FileCheck /home/asiemien/tpp-sandbox/test/Benchmarks/simple-gemm.mlir
: 'RUN: at line 12';   /home/asiemien/tpp-sandbox/build/bin/tpp-opt /home/asiemien/tpp-sandbox/test/Benchmarks/simple-gemm.mlir -map-linalg-to-tpp  -one-shot-bufferize="bufferize-function-boundaries allow-return-allocs function-boundary-type-conversion=identity-layout-map"  -drop-equivalent-buffer-results -finalizing-bufferize -canonicalize  -convert-linalg-to-tpp | /home/asiemien/llvm-project/build/bin/FileCheck -check-prefix=TPP /home/asiemien/tpp-sandbox/test/Benchmarks/simple-gemm.mlir
--
Exit Code: 2

Command Output (stderr):
--
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /home/asiemien/tpp-sandbox/build/bin/tpp-run -e entry -entry-point-result=void -shared-libs=/home/asiemien/llvm-project/build/./lib/libmlir_c_runner_utils.so,/home/asiemien/tpp-sandbox/build/lib//libtpp_c_runner_utils.so
 #0 0x0000559cc3da24f3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/asiemien/llvm-project/llvm/lib/Support/Unix/Signals.inc:569:13
 #1 0x0000559cc3da0790 llvm::sys::RunSignalHandlers() /home/asiemien/llvm-project/llvm/lib/Support/Signals.cpp:105:18
 #2 0x0000559cc3da2b3f SignalHandler(int) /home/asiemien/llvm-project/llvm/lib/Support/Unix/Signals.inc:407:1
 #3 0x00007f84ce8f5420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x0000559cc4da54d7 std::__uniq_ptr_impl<mlir::MLIRContextImpl, std::default_delete<mlir::MLIRContextImpl>>::_M_ptr() const /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:154:42
 #5 0x0000559cc4da54d7 std::unique_ptr<mlir::MLIRContextImpl, std::default_delete<mlir::MLIRContextImpl>>::get() const /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:361:21
 #6 0x0000559cc4da54d7 std::unique_ptr<mlir::MLIRContextImpl, std::default_delete<mlir::MLIRContextImpl>>::operator*() const /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:347:10
 #7 0x0000559cc4da54d7 mlir::MLIRContext::getImpl() /home/asiemien/llvm-project/mlir/include/mlir/IR/MLIRContext.h:197:39
 #8 0x0000559cc4da54d7 mlir::RegisteredOperationName::lookup(llvm::StringRef, mlir::MLIRContext*) /home/asiemien/llvm-project/mlir/lib/IR/MLIRContext.cpp:750:21
 #9 0x0000559cc3d69bca mlir::RegisteredOperationName mlir::OpBuilder::getCheckRegisteredInfo<mlir::vector::PrintOp>(mlir::MLIRContext*) /home/asiemien/llvm-project/mlir/include/mlir/IR/Builders.h:443:5
#10 0x0000559cc3d69bca mlir::vector::PrintOp mlir::OpBuilder::create<mlir::vector::PrintOp, mlir::vector::TransferReadOp&>(mlir::Location, mlir::vector::TransferReadOp&) /home/asiemien/llvm-project/mlir/include/mlir/IR/Builders.h:458:20
#11 0x0000559cc3d69bca prepareMLIRKernel(mlir::Operation*) /home/asiemien/tpp-sandbox/build/../tpp-run/tpp-run.cpp:254:48
#12 0x0000559cc4dcda9d mlir::LogicalResult::failed() const /home/asiemien/llvm-project/mlir/include/mlir/Support/LogicalResult.h:44:33
#13 0x0000559cc4dcda9d mlir::failed(mlir::LogicalResult) /home/asiemien/llvm-project/mlir/include/mlir/Support/LogicalResult.h:72:58
#14 0x0000559cc4dcda9d mlir::JitRunnerMain(int, char**, mlir::DialectRegistry const&, mlir::JitRunnerConfig) /home/asiemien/llvm-project/mlir/lib/ExecutionEngine/JitRunner.cpp:368:9
#15 0x0000559cc3d133c7 std::vector<std::unique_ptr<mlir::DialectExtensionBase, std::default_delete<mlir::DialectExtensionBase>>, std::allocator<std::unique_ptr<mlir::DialectExtensionBase, std::default_delete<mlir::DialectExtensionBase>>>>::~vector() /usr/include/c++/9/bits/stl_vector.h:677:15
#16 0x0000559cc3d133c7 mlir::DialectRegistry::~DialectRegistry() /home/asiemien/llvm-project/mlir/include/mlir/IR/DialectRegistry.h:109:7
#17 0x0000559cc3d133c7 main /home/asiemien/tpp-sandbox/build/../tpp-run/tpp-run.cpp:287:19
#18 0x00007f84ce38f083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#19 0x0000559cc3d64f1e _start (/home/asiemien/tpp-sandbox/build/bin/tpp-run+0x2dff1e)
```

I have seen similar errors before but I thought I had fixed them all. Since this code is in constant flux at the moment (work in progress, tracked by #74), I may have fixed already locally, too.

I'll test this again after the next merge, which should make it much easier to fix this problem, as I'm factoring out everything in smaller methods of a benchmark class.

@adam-smnk

**Comment by rengolin** [comment]
I have tried reproducing this, but cannot see the same error.
Main at `c8e28c1`, LLVM at `c2c48f0c9693`, cmake command:
```
cmake -G Ninja \
      -DMLIR_DIR=.../llvm-project/build/sandbox/lib/cmake/mlir \
      -DLLVM_EXTERNAL_LIT=.../llvm-project/build/sandbox/bin/llvm-lit
```
GCC version 12.2.0.

I still only get the errors in #45 with release LLVM builds and no errors with debug LLVM builds.

**Comment by rengolin** [comment]
@chelini @KavithaTipturMadhu @adam-smnk I think I have fixed this with #174. If you can check again and :+1: this comment if its now working for you, I can close this issue. Thanks!

**Comment by adam-smnk** [comment]
Works perfect on tpp-sandbox built using clang.

The original issue from this ticket is no longer present.
However, my local GCC 9.4.0 build has some new problems. For completeness, I will them here:
```
[0/2] Re-checking globbed directories...
[0/1] Running the tpp-opt regression tests
-- Testing: 72 tests, 16 workers --
Testing: 
FAIL: TPP_OPT :: Integration/tpp-relu.mlir (1 of 72)
******************** TEST 'TPP_OPT :: Integration/tpp-relu.mlir' FAILED ********************
Script:
--
: 'RUN: at line 2';   /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-opt /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-relu.mlir -map-linalg-to-tpp -one-shot-bufferize="bufferize-function-boundaries allow-return-allocs function-boundary-type-conversion=identity-layout-map"  -canonicalize -drop-equivalent-buffer-results -finalizing-bufferize -convert-linalg-to-tpp -convert-tpp-to-loops -arith-expand -convert-vector-to-scf -convert-scf-to-cf |  /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-run   -e entry -entry-point-result=void   -shared-libs=/home/asiemien/llvm-project/build/./lib/libmlir_c_runner_utils.so |  /home/asiemien/llvm-project/build/bin/FileCheck /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-relu.mlir
: 'RUN: at line 10';   /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-opt /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-relu.mlir -map-linalg-to-tpp -one-shot-bufferize="bufferize-function-boundaries allow-return-allocs function-boundary-type-conversion=identity-layout-map"  -canonicalize -drop-equivalent-buffer-results -finalizing-bufferize -convert-linalg-to-tpp -convert-tpp-to-xsmm -convert-xsmm-to-func -arith-expand -convert-vector-to-scf -convert-scf-to-cf |  /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-run   -e entry -entry-point-result=void   -shared-libs=/home/asiemien/llvm-project/build/./lib/libmlir_c_runner_utils.so,/home/asiemien/plaidml-tpp-sandbox/build/lib//libtpp_c_runner_utils.so |  /home/asiemien/llvm-project/build/bin/FileCheck /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-relu.mlir
: 'RUN: at line 18';   /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-opt /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-relu.mlir -map-linalg-to-tpp -one-shot-bufferize="bufferize-function-boundaries allow-return-allocs function-boundary-type-conversion=identity-layout-map"  -canonicalize -drop-equivalent-buffer-results -finalizing-bufferize -convert-linalg-to-tpp | /home/asiemien/llvm-project/build/bin/FileCheck -check-prefix=TPP /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-relu.mlir
--
Exit Code: 2

Command Output (stderr):
--
loc("<stdin>":4:1): error: Entry point already created, use mlir-cpu-runner
JIT session error: Symbols not found: [ _mlir_ciface_timer_alloc, _mlir_ciface_timer_average, _mlir_ciface_timer_deviation, _mlir_ciface_timer_start, _mlir_ciface_timer_stop ]
Error: Failed to materialize symbols: { (main, { timer_average, _mlir_timer_deviation, timer_deviation, entry, relutpp, _mlir_relutpp, timer_alloc, timer_start, _mlir_timer_stop, timer_stop, _mlir_timer_average, _mlir_timer_alloc, _mlir_timer_start, _mlir_entry, _mlir__mlir_ciface_relutpp, _mlir_ciface_relutpp }) }
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /home/asiemien/llvm-project/build/bin/FileCheck /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-relu.mlir

--

********************
Testing: 
FAIL: TPP_OPT :: Integration/tpp-brgemm-non-unit-batch.mlir (2 of 72)
******************** TEST 'TPP_OPT :: Integration/tpp-brgemm-non-unit-batch.mlir' FAILED ********************
Script:
--
: 'RUN: at line 1';   /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-opt /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-brgemm-non-unit-batch.mlir -one-shot-bufferize="bufferize-function-boundaries allow-return-allocs function-boundary-type-conversion=identity-layout-map"  -canonicalize -drop-equivalent-buffer-results -finalizing-bufferize -convert-linalg-to-tpp -convert-tpp-to-loops -convert-linalg-to-loops -convert-vector-to-scf -convert-scf-to-cf |  /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-run   -e entry -entry-point-result=void   -shared-libs=/home/asiemien/llvm-project/build/./lib/libmlir_c_runner_utils.so |  /home/asiemien/llvm-project/build/bin/FileCheck /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-brgemm-non-unit-batch.mlir
: 'RUN: at line 8';   /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-opt /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-brgemm-non-unit-batch.mlir -map-linalg-to-tpp -one-shot-bufferize="bufferize-function-boundaries allow-return-allocs function-boundary-type-conversion=identity-layout-map"  -canonicalize -drop-equivalent-buffer-results -finalizing-bufferize -convert-linalg-to-tpp -convert-tpp-to-xsmm -convert-xsmm-to-func -convert-vector-to-scf -convert-scf-to-cf |  /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-run   -e entry -entry-point-result=void   -shared-libs=/home/asiemien/llvm-project/build/./lib/libmlir_c_runner_utils.so,/home/asiemien/plaidml-tpp-sandbox/build/lib//libtpp_c_runner_utils.so |  /home/asiemien/llvm-project/build/bin/FileCheck /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-brgemm-non-unit-batch.mlir
: 'RUN: at line 16';   /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-opt /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-brgemm-non-unit-batch.mlir -map-linalg-to-tpp -one-shot-bufferize="bufferize-function-boundaries allow-return-allocs function-boundary-type-conversion=identity-layout-map"  -canonicalize -drop-equivalent-buffer-results -finalizing-bufferize -convert-linalg-to-tpp | /home/asiemien/llvm-project/build/bin/FileCheck -check-prefix=TPP /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-brgemm-non-unit-batch.mlir
--
Exit Code: 2

Command Output (stderr):
--
loc("<stdin>":5:1): error: Entry point already created, use mlir-cpu-runner
JIT session error: Symbols not found: [ _mlir_ciface_timer_alloc, _mlir_ciface_timer_average, _mlir_ciface_timer_deviation, _mlir_ciface_timer_start, _mlir_ciface_timer_stop ]
Error: Failed to materialize symbols: { (main, { _mlir__mlir_ciface_brgemmtpp, _mlir_timer_alloc, timer_alloc, _mlir_ciface_brgemmtpp, _mlir_brgemmtpp, _mlir_entry, _mlir_timer_deviation, timer_stop, timer_deviation, _mlir_timer_average, timer_average, _mlir_timer_stop, entry, timer_start, _mlir_timer_start, brgemmtpp }) }
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /home/asiemien/llvm-project/build/bin/FileCheck /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-brgemm-non-unit-batch.mlir

--
...
```
The errors are the same for all the following tests:
```
  TPP_OPT :: Integration/copy.mlir
  TPP_OPT :: Integration/matmul-tpp-with-print.mlir
  TPP_OPT :: Integration/simple-copy.mlir
  TPP_OPT :: Integration/smoke.mlir
  TPP_OPT :: Integration/tiling-add.mlir
  TPP_OPT :: Integration/tiling-relu.mlir
  TPP_OPT :: Integration/tpp-brgemm-non-unit-batch.mlir
  TPP_OPT :: Integration/tpp-brgemm.mlir
  TPP_OPT :: Integration/tpp-matmul.mlir
  TPP_OPT :: Integration/tpp-relu.mlir
```
But again, it happens only on GCC. Also, the dumps from #45 are also present in GCC version.

**Comment by chelini** [comment]
> Works perfect on tpp-sandbox built using clang.
> 
> The original issue from this ticket is no longer present. However, my local GCC 9.4.0 build has some new problems. For completeness, I will leave them here:
> 
> ```
> [0/2] Re-checking globbed directories...
> [0/1] Running the tpp-opt regression tests
> -- Testing: 72 tests, 16 workers --
> Testing: 
> FAIL: TPP_OPT :: Integration/tpp-relu.mlir (1 of 72)
> ******************** TEST 'TPP_OPT :: Integration/tpp-relu.mlir' FAILED ********************
> Script:
> --
> : 'RUN: at line 2';   /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-opt /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-relu.mlir -map-linalg-to-tpp -one-shot-bufferize="bufferize-function-boundaries allow-return-allocs function-boundary-type-conversion=identity-layout-map"  -canonicalize -drop-equivalent-buffer-results -finalizing-bufferize -convert-linalg-to-tpp -convert-tpp-to-loops -arith-expand -convert-vector-to-scf -convert-scf-to-cf |  /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-run   -e entry -entry-point-result=void   -shared-libs=/home/asiemien/llvm-project/build/./lib/libmlir_c_runner_utils.so |  /home/asiemien/llvm-project/build/bin/FileCheck /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-relu.mlir
> : 'RUN: at line 10';   /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-opt /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-relu.mlir -map-linalg-to-tpp -one-shot-bufferize="bufferize-function-boundaries allow-return-allocs function-boundary-type-conversion=identity-layout-map"  -canonicalize -drop-equivalent-buffer-results -finalizing-bufferize -convert-linalg-to-tpp -convert-tpp-to-xsmm -convert-xsmm-to-func -arith-expand -convert-vector-to-scf -convert-scf-to-cf |  /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-run   -e entry -entry-point-result=void   -shared-libs=/home/asiemien/llvm-project/build/./lib/libmlir_c_runner_utils.so,/home/asiemien/plaidml-tpp-sandbox/build/lib//libtpp_c_runner_utils.so |  /home/asiemien/llvm-project/build/bin/FileCheck /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-relu.mlir
> : 'RUN: at line 18';   /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-opt /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-relu.mlir -map-linalg-to-tpp -one-shot-bufferize="bufferize-function-boundaries allow-return-allocs function-boundary-type-conversion=identity-layout-map"  -canonicalize -drop-equivalent-buffer-results -finalizing-bufferize -convert-linalg-to-tpp | /home/asiemien/llvm-project/build/bin/FileCheck -check-prefix=TPP /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-relu.mlir
> --
> Exit Code: 2
> 
> Command Output (stderr):
> --
> loc("<stdin>":4:1): error: Entry point already created, use mlir-cpu-runner
> JIT session error: Symbols not found: [ _mlir_ciface_timer_alloc, _mlir_ciface_timer_average, _mlir_ciface_timer_deviation, _mlir_ciface_timer_start, _mlir_ciface_timer_stop ]
> Error: Failed to materialize symbols: { (main, { timer_average, _mlir_timer_deviation, timer_deviation, entry, relutpp, _mlir_relutpp, timer_alloc, timer_start, _mlir_timer_stop, timer_stop, _mlir_timer_average, _mlir_timer_alloc, _mlir_timer_start, _mlir_entry, _mlir__mlir_ciface_relutpp, _mlir_ciface_relutpp }) }
> FileCheck error: '<stdin>' is empty.
> FileCheck command line:  /home/asiemien/llvm-project/build/bin/FileCheck /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-relu.mlir
> 
> --
> 
> ********************
> Testing: 
> FAIL: TPP_OPT :: Integration/tpp-brgemm-non-unit-batch.mlir (2 of 72)
> ******************** TEST 'TPP_OPT :: Integration/tpp-brgemm-non-unit-batch.mlir' FAILED ********************
> Script:
> --
> : 'RUN: at line 1';   /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-opt /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-brgemm-non-unit-batch.mlir -one-shot-bufferize="bufferize-function-boundaries allow-return-allocs function-boundary-type-conversion=identity-layout-map"  -canonicalize -drop-equivalent-buffer-results -finalizing-bufferize -convert-linalg-to-tpp -convert-tpp-to-loops -convert-linalg-to-loops -convert-vector-to-scf -convert-scf-to-cf |  /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-run   -e entry -entry-point-result=void   -shared-libs=/home/asiemien/llvm-project/build/./lib/libmlir_c_runner_utils.so |  /home/asiemien/llvm-project/build/bin/FileCheck /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-brgemm-non-unit-batch.mlir
> : 'RUN: at line 8';   /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-opt /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-brgemm-non-unit-batch.mlir -map-linalg-to-tpp -one-shot-bufferize="bufferize-function-boundaries allow-return-allocs function-boundary-type-conversion=identity-layout-map"  -canonicalize -drop-equivalent-buffer-results -finalizing-bufferize -convert-linalg-to-tpp -convert-tpp-to-xsmm -convert-xsmm-to-func -convert-vector-to-scf -convert-scf-to-cf |  /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-run   -e entry -entry-point-result=void   -shared-libs=/home/asiemien/llvm-project/build/./lib/libmlir_c_runner_utils.so,/home/asiemien/plaidml-tpp-sandbox/build/lib//libtpp_c_runner_utils.so |  /home/asiemien/llvm-project/build/bin/FileCheck /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-brgemm-non-unit-batch.mlir
> : 'RUN: at line 16';   /home/asiemien/plaidml-tpp-sandbox/build/bin/tpp-opt /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-brgemm-non-unit-batch.mlir -map-linalg-to-tpp -one-shot-bufferize="bufferize-function-boundaries allow-return-allocs function-boundary-type-conversion=identity-layout-map"  -canonicalize -drop-equivalent-buffer-results -finalizing-bufferize -convert-linalg-to-tpp | /home/asiemien/llvm-project/build/bin/FileCheck -check-prefix=TPP /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-brgemm-non-unit-batch.mlir
> --
> Exit Code: 2
> 
> Command Output (stderr):
> --
> loc("<stdin>":5:1): error: Entry point already created, use mlir-cpu-runner
> JIT session error: Symbols not found: [ _mlir_ciface_timer_alloc, _mlir_ciface_timer_average, _mlir_ciface_timer_deviation, _mlir_ciface_timer_start, _mlir_ciface_timer_stop ]
> Error: Failed to materialize symbols: { (main, { _mlir__mlir_ciface_brgemmtpp, _mlir_timer_alloc, timer_alloc, _mlir_ciface_brgemmtpp, _mlir_brgemmtpp, _mlir_entry, _mlir_timer_deviation, timer_stop, timer_deviation, _mlir_timer_average, timer_average, _mlir_timer_stop, entry, timer_start, _mlir_timer_start, brgemmtpp }) }
> FileCheck error: '<stdin>' is empty.
> FileCheck command line:  /home/asiemien/llvm-project/build/bin/FileCheck /home/asiemien/plaidml-tpp-sandbox/test/Integration/tpp-brgemm-non-unit-batch.mlir
> 
> --
> ...
> ```
> 
> The errors are the same for all the following tests:
> 
> ```
>   TPP_OPT :: Integration/copy.mlir
>   TPP_OPT :: Integration/matmul-tpp-with-print.mlir
>   TPP_OPT :: Integration/simple-copy.mlir
>   TPP_OPT :: Integration/smoke.mlir
>   TPP_OPT :: Integration/tiling-add.mlir
>   TPP_OPT :: Integration/tiling-relu.mlir
>   TPP_OPT :: Integration/tpp-brgemm-non-unit-batch.mlir
>   TPP_OPT :: Integration/tpp-brgemm.mlir
>   TPP_OPT :: Integration/tpp-matmul.mlir
>   TPP_OPT :: Integration/tpp-relu.mlir
> ```
> 
> But again, it happens only on GCC. Also, the dumps from #45 are also present in GCC version.

This https://github.com/plaidml/tpp-sandbox/pull/178 should fix your issue. I suggest the following rule: use `tpp-run` only for benchmarking and use `mlir-cpu-runner` for all the rest.

**Comment by rengolin** [comment]
Ok, I'm going to close this issue and we can follow other issues by creating new ones.
