### ISSUE TITLE
LinalgX:relayout.

### ISSUE THREAD

**Issue by chelini** [plaidml/tpp-sandbox#19]
the relayout op should be upstreamed. But we want to have a `pack` and `unpack` operation, not in Linalg but in the Tenor and then memref dialect. We are not supposed to use maps anymore but a combination of attributes (tiling factors along the dimensions + transpose - how you want to relayout the dimensions).

**Comment by nicolasvasilache** [comment]
Tile/untile or block/unblock would work too but these names are very overloaded already.

Data packing/unpacking is common HPC terminology (see e.g. BLIS), the fact that TF names this concept differently (and somewhat conflates it with tf.Concat ...) is not a good reason to diverge IMO.

**Comment by nicolasvasilache** [comment]
In terms of semantics: 
- `tensor.pack == tensor.pad + tensor.expand_shape + tensor.transpose`
- `tensor.unpack == tensor.extract_slice + tensor.transpose + tensor.collapse_shape`

This does beg the question of whether we really want a new op here, I'd be interested in a discussion on that specific topic to see whether we really need this op.

**Comment by rengolin** [comment]
IIUC, TF's pack/unpack has a similar purpose (dense computation) but for a specific purpose (mostly convolution?) so with completely different implementation.

I don't want to create an op that has combined semantics, which makes it harder to discuss each sub-semantics, especially if there are already ops that can be used.

If the proposed `pack`/`unpack` can already be implemented by a sequence of ops, than I'll always favour using them instead.

@chelini let's go through our uses of `relayout` and see how we can use tensor's ops instead. Only what's missing that we shall propose additions to the tensor dialect.

**Comment by rengolin** [comment]
I may be wrong, but I imagine that having sub-ops on tensors will also make it easier to match it with `transform` ops 1:1 once we start using them.

**Comment by MaheshRavishankar** [comment]
In IREE we have been using `tensor.pad + tensor.expand_shape + tensor.transpose` (as well as the unpack sequence) for a while now. IMO this is too general a representation and drops a lot of semantics making it harder to codegen for. There are two advantages with having a dedicated `pack` and `unpack` operation
1) If these operations implement the `TilingInterface`, they naturally fit into the Tile + Fuse framework and "should" fuse with producers.
2) Also interesting in supporting a backend that is not LLVM based. Having a pack and unpack operation can give us a way to use microkernels to do this if needed (though we might not need it).

**Comment by MaheshRavishankar** [comment]
Had an offline chat with Nicolas, and we were wondering if there is a way to experiment more with IREE to iterate with multiple use cases and then upstream. For context, we've been considering the following operation. (Note: the following doesnt use destination passing style, but it probably should which I am ignoring for now)

```
%tiled = tensor.pack_and_pad %source inner_tile_dims[%tilea, %tileb]  : tensor<?x?xf32> -> tensor<?x?x?x?xf32>
```

and its dual

```
%untiled = tensor.unpack_and_extract %tiled inner_tile_dims[%tilea, %tileb] : tensor<?x?x?x?xf32> -> tensor<?x?xf32>
```

This only does a simple packing and unpacking (to start with). A slight variant of the packing up (where the inner tile dimensions are known) could be

```
%tiled = tensor.pack_and_pad %source inner_tile_dims[8, 4] : tensor<?x?xf32> -> tensor<?x?xvector<8x4xf32>>
```

This introduces some alignment information as well which is useful. Note we also considered a

```
%tiled = tensor.pack_and_pad %source inner_tile_dims[%tilea, %tileb]  : tensor<?x?xf32> -> tensor<?x?xtensor<?x?xf32>>
```

but tensor of tensors is not supported upstream right now, and also doesn't seem like we need to front load that to start with, so decided to revisit this design point later on if needed.

I dont know all the details of the relayout op here, but it might be worth experimenting within IREE itself. We were planning to initially iterate on the pack and unpack operations in IREE (within `linalg_ext`) and then upstream. Maybe `linalg_ext` is a way for us to iterate on design collectively, i.e. use these ops in IREE e2e first to prototype, and flush out the design more. Please let me know if that is of interest to you folks. (Just to clarify, you guys don't have to even touch IREE. We will connect this e2e and keep you in the loop as we get this working. This is just a way to inform each other of what worked in IREE and what needed to be tweaked, and you can keep us in the loop as well if you iterate on this op more before upstreaming it).

**Comment by rengolin** [comment]
The PR to IREE has been merged, do we need to do anything else in this issue?

https://github.com/iree-org/iree/pull/10481

**Comment by chelini** [comment]
> The PR to IREE has been merged, do we need to do anything else in this issue?
> 
> [iree-org/iree#10481](https://github.com/iree-org/iree/pull/10481)

I think we can close.
